import Head from "next/head";
import Image from "next/image";
import { Roboto } from "@next/font/google";
import Button from "../components/button";
import SmallBadge from "../components/smallBadge";
import Carousel from "../components/carousel";
import Popular from "../components/popular";
import picture1 from "../static-img/popular10.jpg";
import picture2 from "../static-img/popular9.jpg";

const roboto = Roboto({
  weight: ["100", "400", "700", "900"],
  style: "normal",
  subsets: ["latin"],
  variable: "--roboto-font",
});

export default function Home() {
  return (
    <div className={roboto.variable}>
      <Head>
        <title>Leylaki Takı</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <section className="sidebar">
          <picture className="sidebar__logo">
            <a href="./" className="sidebar__logo--mask">
              Leylaki
            </a>
          </picture>
          <a href="./taki" className="sidebar__takilar">
            Takilar
          </a>
          <a href="./hediyelik-esya" className="sidebar__hediyelik-esyalar">
            Hediyelik Esyalar
          </a>
        </section>
        <section className="slider">
          <Carousel />
        </section>
        <section className="popular">
          <Popular />
        </section>
        {/* <section className="categories">
          <picture className="categories__item">
            <Image src={picture1} width={500} height={250} alt="Takı" />
          </picture>
          <picture className="categories__item">
            <Image src={picture2} width={500} height={250} alt="Takı" />
          </picture>
        </section> */}
        <section className="footer">
          <a href="#" className="footer__element">
            Hakkımızda
          </a>
          <a href="#" className="footer__element">
            iletişim
          </a>
          <a href="#" className="footer__element">
            istek ve öneriler
          </a>
          <a href="#" className="footer__element">
            Her Hakkı Saklıdır
          </a>
        </section>
      </main>
    </div>
  );
}
